// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {ERC1967Proxy} from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";

import {Snaxpot} from "../src/Snaxpot.sol";
import {ISnaxpot} from "../src/interfaces/ISnaxpot.sol";
import {IJackpotClaimer} from "../src/interfaces/IJackpotClaimer.sol";
import {IVRFCoordinatorV2Plus} from "../src/chainlink/interfaces/IVRFCoordinatorV2Plus.sol";
import {VRFV2PlusClient} from "../src/chainlink/libraries/VRFV2PlusClient.sol";

import {MockERC20} from "./mocks/MockERC20.sol";

contract SnaxpotTest is Test {
    address admin;
    address operator;
    address alice;
    address bob;

    MockERC20 usdt;
    address vrfCoordinator;
    address jackpotClaimer;
    Snaxpot snaxpot;

    uint256 constant VRF_SUB_ID = 1;
    bytes32 constant VRF_KEY_HASH = bytes32(uint256(0xdead));
    uint32 constant VRF_CALLBACK_GAS = 500_000;
    uint16 constant VRF_CONFIRMATIONS = 3;

    uint256 constant VRF_REQUEST_ID = 1;
    uint256 constant JACKPOT_FUND = 1000e6;

    // ─── Merkle fixtures ────────────────────────────────────────────
    // Generated by: forge script script/GenerateMerkleForTests.s.sol -v
    //
    // VRF draws:
    //   DRAW_A: words [10,20,30,40,50,3]     → balls [9,11,19,21,31] snaxBall 4 (multi-winner)
    //   DRAW_B: words [1,2,3,4,5,0]          → balls [2,3,4,5,6]     snaxBall 1 (no winner)
    //   DRAW_C: words [100,200,300,400,500,7] → balls [5,9,13,17,21] snaxBall 3 (single-winner)
    //
    // 4 tickets (balls sorted):
    //   [0] alice | [9,11,19,21,31]  | snaxBall 4 | idx 0  → matches DRAW_A
    //   [1] bob   | [9,11,19,21,31]  | snaxBall 4 | idx 0  → matches DRAW_A
    //   [2] alice | [5,9,13,17,21]   | snaxBall 3 | idx 1  → matches DRAW_C
    //   [3] bob   | [1,7,12,20,28]   | snaxBall 2 | idx 1  → matches neither
    bytes32 constant MERKLE_ROOT =
        0xd2bfa9184f92b4541c8a5bac90707dac540e56846ee0b828acbf47648203ae9e;

    bytes32 constant LEAF_0 =
        0x9df0a167364098ea1175a7304fb63e3f2c166e61c5609a9975b116fb9e23d6b3;
    bytes32 constant LEAF_1 =
        0x7a2736475d1e90a8e50dc49c2732441be24b234c3e21b41069cb9a50002f1ecf;
    bytes32 constant LEAF_2 =
        0xb5d7d2d2e177971f8fb479f830fdfa48d3211c5f0031e4646c00e584fe4415c6;
    bytes32 constant LEAF_3 =
        0x315b7e24d032df9ed10ce96f70085398241b7eb20516b300517274f80917cb67;

    bytes32 constant H01 =
        0x76f1d25323b8ca98b2ca15371dea798cfd7f5b2a2cafbe217869ef217a076bbc;
    bytes32 constant H23 =
        0x9bc1b7e3d91372025ba74777763aaa31508f86e365ab2af4e552ad127fa67dec;

    function setUp() public {
        admin = makeAddr("admin");
        operator = makeAddr("operator");
        alice = makeAddr("alice");
        bob = makeAddr("bob");

        usdt = new MockERC20("Tether USD", "USDT", 6);
        vrfCoordinator = makeAddr("vrfCoordinator");
        jackpotClaimer = makeAddr("jackpotClaimer");

        vm.mockCall(
            jackpotClaimer,
            abi.encodeWithSelector(IJackpotClaimer.credit.selector),
            abi.encode()
        );
        vm.mockCall(
            vrfCoordinator,
            abi.encodeWithSelector(
                IVRFCoordinatorV2Plus.requestRandomWords.selector
            ),
            abi.encode(VRF_REQUEST_ID)
        );

        Snaxpot impl = new Snaxpot();
        bytes memory initData = abi.encodeCall(
            Snaxpot.initialize,
            (
                admin,
                operator,
                address(usdt),
                jackpotClaimer,
                vrfCoordinator,
                VRF_SUB_ID,
                VRF_KEY_HASH,
                VRF_CALLBACK_GAS,
                VRF_CONFIRMATIONS
            )
        );
        snaxpot = Snaxpot(address(new ERC1967Proxy(address(impl), initData)));
    }

    // ─── VRF helper ─────────────────────────────────────────────────

    function _fulfillVrf(uint256[] memory words) internal {
        vm.startPrank(vrfCoordinator);
        snaxpot.rawFulfillRandomWords(VRF_REQUEST_ID, words);
        vm.stopPrank();
    }

    // Known VRF word → ball mappings (no collisions):
    //
    //   DRAW_A: words [10, 20, 30, 40, 50, 3]  → balls [11, 21, 31, 9, 19], snaxBall 4
    //   DRAW_B: words [100, 200, 300, 400, 500, 7] → balls [5, 9, 13, 17, 21], snaxBall 3
    //
    /// @dev Mirrors Snaxpot._deriveBalls so tests can predict winning numbers from VRF words.
    function _deriveBalls(
        uint256[] memory randomWords
    ) internal pure returns (uint8[5] memory balls, uint8 snaxBall) {
        uint256 usedMask;
        uint8 count;
        for (uint8 i = 0; count < 5; i++) {
            uint256 rand = i < 5
                ? randomWords[i]
                : uint256(keccak256(abi.encodePacked(randomWords[i - 1], i)));
            uint8 ball = uint8((rand % 32) + 1);
            uint256 bit = uint256(1) << ball;
            if (usedMask & bit == 0) {
                usedMask |= bit;
                balls[count++] = ball;
            } else {
                uint256 h = rand;
                while (usedMask & bit != 0) {
                    h = uint256(keccak256(abi.encodePacked(h)));
                    ball = uint8((h % 32) + 1);
                    bit = uint256(1) << ball;
                }
                usedMask |= bit;
                balls[count++] = ball;
            }
        }
        snaxBall = uint8((randomWords[5] % 5) + 1);
    }

    function _fundJackpot() internal {
        usdt.mint(alice, JACKPOT_FUND);
        vm.startPrank(alice);
        usdt.approve(address(snaxpot), JACKPOT_FUND);
        snaxpot.fundJackpot(JACKPOT_FUND);
        vm.stopPrank();
    }

    /// @dev DRAW_B → balls [2,3,4,5,6] snaxBall 1. No ticket matches.
    function _setUpDrawnEpochNoWinner() internal returns (uint256 epochId) {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        epochId = snaxpot.currentEpochId();
        _fundJackpot();
        vm.startPrank(operator);
        snaxpot.closeEpoch(epochId);
        snaxpot.commitMerkleRootAndDraw(epochId, MERKLE_ROOT);
        vm.stopPrank();

        uint256[] memory words = new uint256[](6);
        words[0] = 1;
        words[1] = 2;
        words[2] = 3;
        words[3] = 4;
        words[4] = 5;
        words[5] = 0;
        _fulfillVrf(words);
    }

    /// @dev DRAW_A → balls [9,11,19,21,31] snaxBall 4. Tickets 0 + 1 match (alice + bob).
    function _setUpDrawnEpochMultiWinner() internal returns (uint256 epochId) {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        epochId = snaxpot.currentEpochId();
        _fundJackpot();
        vm.startPrank(operator);
        snaxpot.closeEpoch(epochId);
        snaxpot.commitMerkleRootAndDraw(epochId, MERKLE_ROOT);
        vm.stopPrank();

        uint256[] memory words = new uint256[](6);
        words[0] = 10;
        words[1] = 20;
        words[2] = 30;
        words[3] = 40;
        words[4] = 50;
        words[5] = 3;
        _fulfillVrf(words);
    }

    /// @dev DRAW_C → balls [5,9,13,17,21] snaxBall 3. Only ticket 2 matches (alice).
    function _setUpDrawnEpochSingleWinner() internal returns (uint256 epochId) {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        epochId = snaxpot.currentEpochId();
        _fundJackpot();
        vm.startPrank(operator);
        snaxpot.closeEpoch(epochId);
        snaxpot.commitMerkleRootAndDraw(epochId, MERKLE_ROOT);
        vm.stopPrank();

        uint256[] memory words = new uint256[](6);
        words[0] = 100;
        words[1] = 200;
        words[2] = 300;
        words[3] = 400;
        words[4] = 500;
        words[5] = 7;
        _fulfillVrf(words);
    }

    // ─── Tests ──────────────────────────────────────────────────────

    function test_initialState() public view {
        assertEq(snaxpot.currentEpochId(), 0);
        assertEq(snaxpot.currentJackpot(), 0);
        assertEq(snaxpot.totalAccountedUSDT(), 0);
        assertEq(address(snaxpot.usdt()), address(usdt));
        assertEq(address(snaxpot.jackpotClaimer()), jackpotClaimer);
        assertFalse(snaxpot.paused());
        assertTrue(snaxpot.hasRole(snaxpot.DEFAULT_ADMIN_ROLE(), admin));
        assertTrue(snaxpot.hasRole(snaxpot.OPERATOR_ROLE(), operator));
    }

    function test_openEpoch_happyPath() public {
        vm.expectCall(
            vrfCoordinator,
            abi.encodeCall(
                IVRFCoordinatorV2Plus.requestRandomWords,
                (
                    VRFV2PlusClient.RandomWordsRequest({
                        keyHash: VRF_KEY_HASH,
                        subId: VRF_SUB_ID,
                        requestConfirmations: VRF_CONFIRMATIONS,
                        callbackGasLimit: VRF_CALLBACK_GAS,
                        numWords: 1,
                        extraArgs: VRFV2PlusClient._argsToBytes(
                            VRFV2PlusClient.ExtraArgsV1({nativePayment: false})
                        )
                    })
                )
            )
        );

        vm.startPrank(operator);
        snaxpot.openEpoch();
        vm.stopPrank();

        assertEq(snaxpot.currentEpochId(), 1);

        ISnaxpot.EpochData memory epoch = snaxpot.getEpoch(1);
        assertEq(uint8(epoch.state), uint8(ISnaxpot.EpochState.OPEN));
        assertEq(epoch.startTimestamp, block.timestamp);
    }

    function test_openEpoch_whenNotOperator_reverts() public {
        vm.startPrank(alice);
        vm.expectRevert();
        snaxpot.openEpoch();
        vm.stopPrank();
    }

    function test_openEpoch_whenPaused_reverts() public {
        vm.startPrank(admin);
        snaxpot.pause();
        vm.stopPrank();

        vm.startPrank(operator);
        vm.expectRevert(ISnaxpot.ContractPaused.selector);
        snaxpot.openEpoch();
        vm.stopPrank();
    }

    function test_closeEpoch_happyPath() public {
        vm.startPrank(operator);
        snaxpot.openEpoch();

        vm.expectEmit(true, false, false, true, address(snaxpot));
        emit ISnaxpot.EpochClosed(1, 0, block.timestamp);

        snaxpot.closeEpoch(1);
        vm.stopPrank();

        ISnaxpot.EpochData memory epoch = snaxpot.getEpoch(1);
        assertEq(uint8(epoch.state), uint8(ISnaxpot.EpochState.CLOSED));
        assertEq(epoch.closeTimestamp, block.timestamp);
        assertEq(epoch.jackpotAmount, 0);
        assertEq(snaxpot.currentJackpot(), 0);
    }

    function test_closeEpoch_whenNotOperator_reverts() public {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        vm.stopPrank();

        vm.startPrank(alice);
        vm.expectRevert();
        snaxpot.closeEpoch(1);
        vm.stopPrank();
    }

    function test_closeEpoch_whenPaused_reverts() public {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        vm.stopPrank();

        vm.startPrank(admin);
        snaxpot.pause();
        vm.stopPrank();

        vm.startPrank(operator);
        vm.expectRevert(ISnaxpot.ContractPaused.selector);
        snaxpot.closeEpoch(1);
        vm.stopPrank();
    }

    function test_closeEpoch_whenEpochNotOpen_reverts() public {
        vm.startPrank(operator);
        vm.expectRevert(
            abi.encodeWithSelector(
                ISnaxpot.InvalidEpochState.selector,
                1,
                ISnaxpot.EpochState.NONE,
                ISnaxpot.EpochState.OPEN
            )
        );
        snaxpot.closeEpoch(1);
        vm.stopPrank();
    }

    function test_closeAndOpenNewEpoch_happyPath() public {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        vm.stopPrank();

        _fundJackpot();

        vm.startPrank(operator);
        snaxpot.closeAndOpenNewEpoch(1);
        vm.stopPrank();

        assertEq(snaxpot.currentEpochId(), 2);

        ISnaxpot.EpochData memory epoch1 = snaxpot.getEpoch(1);
        assertEq(uint8(epoch1.state), uint8(ISnaxpot.EpochState.CLOSED));
        assertEq(epoch1.jackpotAmount, JACKPOT_FUND);

        ISnaxpot.EpochData memory epoch2 = snaxpot.getEpoch(2);
        assertEq(uint8(epoch2.state), uint8(ISnaxpot.EpochState.OPEN));
        assertEq(epoch2.startTimestamp, block.timestamp);
        assertEq(epoch2.jackpotAmount, 0);

        assertEq(snaxpot.currentJackpot(), 0);
    }

    function test_commitMerkleRootAndDraw_happyPath() public {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        snaxpot.closeEpoch(1);

        vm.expectCall(
            vrfCoordinator,
            abi.encodeCall(
                IVRFCoordinatorV2Plus.requestRandomWords,
                (
                    VRFV2PlusClient.RandomWordsRequest({
                        keyHash: VRF_KEY_HASH,
                        subId: VRF_SUB_ID,
                        requestConfirmations: VRF_CONFIRMATIONS,
                        callbackGasLimit: VRF_CALLBACK_GAS,
                        numWords: 6,
                        extraArgs: VRFV2PlusClient._argsToBytes(
                            VRFV2PlusClient.ExtraArgsV1({nativePayment: false})
                        )
                    })
                )
            )
        );

        vm.expectEmit(true, false, false, true, address(snaxpot));
        emit ISnaxpot.MerkleRootCommitted(1, MERKLE_ROOT);

        snaxpot.commitMerkleRootAndDraw(1, MERKLE_ROOT);
        vm.stopPrank();

        ISnaxpot.EpochData memory epoch = snaxpot.getEpoch(1);
        assertEq(uint8(epoch.state), uint8(ISnaxpot.EpochState.DRAWING));
        assertEq(epoch.merkleRoot, MERKLE_ROOT);
        assertEq(epoch.vrfRequestId, VRF_REQUEST_ID);
    }

    function test_commitMerkleRootAndDraw_whenNotOperator_reverts() public {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        snaxpot.closeEpoch(1);
        vm.stopPrank();

        vm.startPrank(alice);
        vm.expectRevert();
        snaxpot.commitMerkleRootAndDraw(1, MERKLE_ROOT);
        vm.stopPrank();
    }

    function test_commitMerkleRootAndDraw_whenPaused_reverts() public {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        snaxpot.closeEpoch(1);
        vm.stopPrank();

        vm.startPrank(admin);
        snaxpot.pause();
        vm.stopPrank();

        vm.startPrank(operator);
        vm.expectRevert(ISnaxpot.ContractPaused.selector);
        snaxpot.commitMerkleRootAndDraw(1, MERKLE_ROOT);
        vm.stopPrank();
    }

    function test_commitMerkleRootAndDraw_whenEpochNotClosed_reverts() public {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        vm.expectRevert(
            abi.encodeWithSelector(
                ISnaxpot.InvalidEpochState.selector,
                1,
                ISnaxpot.EpochState.OPEN,
                ISnaxpot.EpochState.CLOSED
            )
        );
        snaxpot.commitMerkleRootAndDraw(1, MERKLE_ROOT);
        vm.stopPrank();
    }

    function test_commitMerkleRootAndDraw_whenZeroRoot_reverts() public {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        snaxpot.closeEpoch(1);
        vm.expectRevert(ISnaxpot.ZeroMerkleRoot.selector);
        snaxpot.commitMerkleRootAndDraw(1, bytes32(0));
        vm.stopPrank();
    }

    function test_fulfillRandomWords_seed_setsVrfSeedAndEmits() public {}

    function test_fulfillRandomWords_draw_happyPath() public {}

    function test_fulfillRandomWords_whenNotCoordinator_reverts() public {}

    function test_resolveJackpotNoWinner_happyPath() public {
        uint256 epochId = _setUpDrawnEpochNoWinner();

        ISnaxpot.EpochData memory epochBefore = snaxpot.getEpoch(epochId);
        assertEq(epochBefore.jackpotAmount, JACKPOT_FUND);

        vm.expectEmit(true, false, false, true, address(snaxpot));
        emit ISnaxpot.JackpotRolledOver(
            epochId,
            uint256(epochBefore.jackpotAmount)
        );

        vm.startPrank(operator);
        snaxpot.resolveJackpotNoWinner(epochId);
        vm.stopPrank();

        ISnaxpot.EpochData memory epoch = snaxpot.getEpoch(epochId);
        assertEq(uint8(epoch.state), uint8(ISnaxpot.EpochState.RESOLVED));
        assertEq(snaxpot.currentJackpot(), JACKPOT_FUND);
    }

    function test_resolveJackpotNoWinner_whenNotOperator_reverts() public {
        uint256 epochId = _setUpDrawnEpochNoWinner();

        vm.startPrank(alice);
        vm.expectRevert();
        snaxpot.resolveJackpotNoWinner(epochId);
        vm.stopPrank();
    }

    function test_resolveJackpotNoWinner_whenPaused_reverts() public {
        uint256 epochId = _setUpDrawnEpochNoWinner();

        vm.startPrank(admin);
        snaxpot.pause();
        vm.stopPrank();

        vm.startPrank(operator);
        vm.expectRevert(ISnaxpot.ContractPaused.selector);
        snaxpot.resolveJackpotNoWinner(epochId);
        vm.stopPrank();
    }

    function test_resolveJackpotNoWinner_whenEpochNotDrawn_reverts() public {
        vm.startPrank(operator);
        snaxpot.openEpoch();
        snaxpot.closeEpoch(1);
        vm.expectRevert(
            abi.encodeWithSelector(
                ISnaxpot.InvalidEpochState.selector,
                1,
                ISnaxpot.EpochState.CLOSED,
                ISnaxpot.EpochState.DRAWN
            )
        );
        snaxpot.resolveJackpotNoWinner(1);
        vm.stopPrank();
    }

    function test_resolveJackpot_singleWinner() public {}

    function test_resolveJackpot_multipleWinners() public {}

    function test_resolveJackpot_whenNotOperator_reverts() public {}

    function test_resolveJackpot_whenPaused_reverts() public {}

    function test_resolveJackpot_whenEpochNotDrawn_reverts() public {}

    function test_resolveJackpot_whenNoWinners_reverts() public {}

    function test_resolveJackpot_whenBallsMismatch_reverts() public {}

    function test_resolveJackpot_whenInvalidMerkleProof_reverts() public {}
}
